### ISSUE TITLE
\n in filename breaks Remove Characters function

### ISSUE THREAD

**Issue by queer-bird** [Nomen-Luni/Bionic-Batch-Renamer#14]
Hello, me again. :)

The issue is attempting to remove the first few characters of these file names with Arabic and Latin scripts mixed. It seems they have to fill some specific requirement in order for this to work as I have had success with some such cases but not others. I have narrowed it down specifically to not working on files like these.

```
21 I like fish أحب السمك.mp3
22 I like fish أحب السمك.mp3
23 I like fish أحب السمك.mp3
```

Out of curiosity I looked at the folder with ls, here is the output.

`'21 I like fish أحب السمك'$'\n''.mp3'  '22 I like fish أحب السمك'$'\n''.mp3'  '23 I like fish أحب السمك'$'\n''.mp3'`

That is some interesting formatting that has been used on these files. Doesn't \n usually indicate a line break? This must be an edge case but I believe this was done so that the number would appear on the left hand side. I notice when I even try to rename these files in dolphin the normal way, first in only shows the part following the \n. So basically the program is reading the filename as two lines and doesn't know what to do with it. That seems to be the problem but I have no idea how hard that would be to fix or if it would even be worth it for such an edge case.

Thank you for your time, your software helps me greatly in my work.

Debian 12 with KDE

**Comment by Nomen-Luni** [comment]
Hi,
Thanks for your revised bug report. It's a weird one.
I do want to fix the bugs (even if it is an unusual edge case.) Real life is on top of me at the moment so in honesty it may be a couple of months before I get around to looking at the outstanding bugs - maybe sooner but no promises.

In the interim, as much as it pains me to recommend 'the competition' you might see if 'thunar bulk rename' works for your edge case. This is part of the Thunar file manager but can be used without using Thunar. It was my inspiration for creating my bulk renamer.

Cheers

**Comment by Nomen-Luni** [comment]
Hello my friend.. I have some time now.

I copied those names you posted and if I do an 'ls' on them they display perfectly fine.
I'm on KDE Neon (based on Ubuntu 22.04).

The issue doesn't appear to be language related. If I try removing the first few characters from:

01 fish and chips.txt
02 fish and chips.txt
03 fish and chips.txt

..same problem. It doesn't work because all 3 files end up with the same name. This is a legitimate bug you've found, because there should be some message saying "you can't do that," which I will put in the next release.

Something you could try to confirm there is no problem related to the language your end, is use the file names you posted but put a unique 1,2,3 as the last character for each one before the extension. Hopefully you will find that the removal of the first few character will then succeed. Please let me know.

**Comment by Nomen-Luni** [comment]
Added appropriate warnings why rename was (legitimately) not performed (see my previous comment.) This will be in the 2.0 release.
