### ISSUE TITLE
can I use captured groups when renaming with regular expressions?

### ISSUE THREAD

**Issue by almaceleste** [Nomen-Luni/Bionic-Batch-Renamer#5]
Hi. I have a question. 
Can I use captured groups when renaming with regular expressions?
Such as `$1`, `$2`...
And if so, can I use math operations with captured group like in Perl? 
Such as `($1+100)`...

**Comment by Nomen-Luni** [comment]
Hi Captanovska,

The answer is I'm not sure, but maybe...

The code uses Qt's "QString.replace" function with QRegular expressions, so it's whatever functionality that brings to the table.

This discussion sounds to me like it's a feature Qt has, https://forum.qt.io/topic/42619/qregularexpression-and-qstring-replace/5

Could you give it a try within the app using that format and let me know? If it doesn't work i'll look a little deeper but I've got a lot going on at the moment so it might be a while.

Cheers

Lee

**Comment by almaceleste** [comment]
Sorry for my late response. 
I have tested this and yes, captured groups work. But not arithmetics. 
And you have to use `\` symbol instead of `$` like in the Thunar Bulk Rename. 
In the screenshot below, you can see the Bionic Batch Renamer on the left side, and the Thunar Bulk Rename on the right side.
![Bionic Batch Renamer vs Thunar Bulk Rename](https://user-images.githubusercontent.com/36765595/185494654-43f5fd8e-6412-4d25-9b6b-6887fa5bfd25.png)

**Comment by Nomen-Luni** [comment]
Thanks almaceleste for looking into this. It's good to know captured groups work.
My aim isn't to produce a carbon copy of Thunar so I'm going to stick with the syntax Qt provides for consistency as in theory people can look at the Qt docs to understand how the regular expressions work.

Regular expressions were really something I only added since it was so simple to do so with it being provided by the framework and I've no plans to add arithmetics as this sounds like it could be quite a bit of effort for what I consider a niche use-case.

With that said if anyone is interested in contributing a patch to add it I would certainly be willing to incorporate it.

I'll leave this open for now in case anyone else wants to comment. Cheers.

**Comment by almaceleste** [comment]
@Nomen-Luni, thanks to reply. 
Regular expression arithmetic is not the target of my issue, especially since I don't know the actual plugin that implements this feature. 
But, on the other hand, regular expressions in general, and capture groups as part of them, without which I cannot imagine using this functionality, are very important to me, cause I usually do renaming using regular expressions. So thanks for implementing this feature.
So, given these two points, I think this issue can be closed. However, I leave it up to you. 
But also I think it's worth making somewhere a wiki or a help about that capture groups in this implementation use `\` instead of the expected `$`, especially because your plugin looks so much like Thunar Bulk Rename. That is why I added an example in the previous comment.

**Comment by Nomen-Luni** [comment]
Yeah agreed this needs some documentation. I've opened a new issue relating to the documentation [https://github.com/Nomen-Luni/Bionic-Batch-Renamer/issues/6](url)

Thanks for the report.
